OliveInvest/Models/ContactModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OliveInvest.Models {
    public class ContactModel {
        public String Name { get; set; }
        public String Phone { get; set; }
        public String Email { get; set; }
        public String Message { get; set; }
    }
}

OliveInvest/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OliveInvest.Controllers
{
    public class AboutUsController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "About Us - Olive Invest";
            return View();
        }
	}
}

OliveInvest/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OliveInvest.Models;
using Newtonsoft.Json;
using System.Web.Configuration;
using System.Net.Mail;
using System.Net;

namespace OliveInvest.Controllers
{
    public class ContactUsController : Controller
    {
        //
        // GET: /ContactUs/
        public ActionResult Index()
        {
            ViewBag.Title = "Contact Us - Olive Invest";
            return View();
        }

        public String sendContactForm(String aoModel) {
            String lsReturn = String.Empty;

            ContactModel loFormData = JsonConvert.DeserializeObject<ContactModel>(aoModel);

            var lsHost = WebConfigurationManager.AppSettings["host"].ToString();

            SmtpClient loMailClient = new SmtpClient();
            loMailClient.Host = lsHost;
            loMailClient.Port = Convert.ToInt32(WebConfigurationManager.AppSettings["port"]);
            loMailClient.EnableSsl = Convert.ToBoolean(WebConfigurationManager.AppSettings["useSSL"]);

            if (Convert.ToBoolean(WebConfigurationManager.AppSettings["useCredentials"])) {
                var lsUsername = WebConfigurationManager.AppSettings["username"].ToString();
                var lsPassword = WebConfigurationManager.AppSettings["password"].ToString();
                NetworkCredential loCredentials = new NetworkCredential(lsUsername, lsPassword);
                loMailClient.Credentials = loCredentials;
            }

            MailMessage loMail = new MailMessage();
            loMail.Sender = new MailAddress(String.Format("office@animatic.rs"));
            
            var loRecipients = WebConfigurationManager.AppSettings["recipients"].ToString().Split(';');
            foreach (var toRecipient in loRecipients) {
                loMail.To.Add(toRecipient);
            }
            var loCCs = WebConfigurationManager.AppSettings["ccs"].ToString().Split(';').ToList<String>();
            loCCs.Where(x => String.IsNullOrEmpty(x) == false).ToList().ForEach(x => loMail.CC.Add(x));
            
            loMail.Subject = WebConfigurationManager.AppSettings["subject"].ToString();
            loMail.IsBodyHtml = true;
            loMail.Body = String.Format("<h3>From: </h3>{0}<h3>Phone: </h3>{1}<h3>Message: </h3>{2}", String.Format("{0} - {1}", loFormData.Name, loFormData.Email), loFormData.Phone, loFormData.Message);
            loMail.From = new MailAddress(String.Format("{0} <{1}>", loFormData.Name, loFormData.Email));

            try
            {
                loMailClient.Send(loMail);
                lsReturn = "Email sent!";
            }
            catch (Exception ex)
            {
                //Error, could not send the message
                lsReturn = "Error occured.";
            }

            return lsReturn;
        }
	}
}

OliveInvest/Controllers/CurrentDevelopmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OliveInvest.Controllers
{
    public class CurrentDevelopmentController : Controller
    {
        //
        // GET: /CurrentDevelopment/
        public ActionResult Index()
        {
            ViewBag.Title = "Current Development - Olive Invest";
            return View();
        }
	}
}

OliveInvest/Controllers/DestinationBokaBayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OliveInvest.Controllers
{
    public class DestinationBokaBayController : Controller
    {
        //
        // GET: /DestinationBokaBay/
        public ActionResult Index()
        {
            ViewBag.Title = "Destination Boka Bay - Olive Invest";
            return View();
        }
	}
}

OliveInvest/Controllers/FutureDevelopmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OliveInvest.Controllers
{
    public class FutureDevelopmentsController : Controller
    {
        //
        // GET: /FutureDevelopments/
        public ActionResult Index()
        {
            ViewBag.Title = "Future Developments - Olive Invest";
            return View();
        }
	}
}

OliveInvest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OliveInvest.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Homepage - Olive Invest ";

            return View();
        }

      
    }
}

OliveInvest/Views/AboutUs/Index.cshtml
<div class="aboutusPage">
    <div class="aboutUs">
        <h1>ABOUT OLIVE INVEST</h1>
        <p>
            Olive Invest is a leading Montenegro luxury real estate development company which quickly cultivated a reputation as a trendsetter. Olive Invest creates high-end residential, commercial, land and mixed-use projects known for originality, attention to detail, and rich quality of community life. Olive Invest develops projects that positively impact and improve lives. <br /><br />
            Each property they take on is selected carefully with a special vision in mind. <br />
            Their passion for Montenegro is displayed by their active role in charitable, civic, arts and cultural organizations.
        </p>
    </div>
</div>
<script>
    $(document).ready(function () {
     
        setHeight("#body");
        setHeight(".homePage");
    });

    $(window).resize(function () {
        setHeight("#body");
        setHeight(".aboutusPage");
    });

    function setHeight(element) {
        var totalHeight = $(window).height();
        var headerHeight = $("header").height();
        var footerHeight = $("footer").height();
        var b = totalHeight - headerHeight - footerHeight;
        $(element).height(b);
    }


</script>

OliveInvest/Views/ContactUs/Index.cshtml
<script src="~/Scripts/ContactUs/ContactUs.js"></script>
<link href='http://fonts.googleapis.com/css?family=Libre+Baskerville' rel='stylesheet' type='text/css'>
<div class="contactUs">
    <div class="contactForm" style="display:none">
        <h1>CONTACT FORM</h1>
        <p style="margin-bottom:30px;">For a full list of our offers or to inquire about future developments please get in touch using informations below. </p>
        <p style="overflow:auto">
            <input style="float:left" type="text" id="name" placeholder="Name" size="40" />
            <input style="float:right" type="text" id="phone" placeholder="Phone (optional)" size="40" />
            <input style="float:left; margin-top:25px;" type="text" id="email" placeholder="Email" size="40" />
        </p>
        <br />

        <textarea placeholder="Type your message here" id="message" cols="40" rows="4"></textarea>
        <br />
        <a id="contactSubmit" style="float: right;font-weight:bold; font-size:12px; padding: 5px 35px 5px 35px; border: 1px solid rgb(223, 177, 92); color: rgb(223, 177, 92); ">SEND</a>
        <p id="validationMessage"></p>
    </div>
</div>
<script>
    $(document).ready(function () {
        setHeight("#body");
        setHeight(".contactUs");

        window.onload(function () {
            setHeight("#body");
            setHeight(".contactUs");
        });
    });



    $(window).resize(function () {
        setHeight("#body");
        setHeight(".contactUs");
   
    });

    function centroralizer(element) {
        var totalWidth = $(window).width();
        var elementWidth = $(element).width();
        var vrednost = (totalWidth - elementWidth) / 2;
        $(element).css('left', vrednost);
    }

    function setHeight(element) {
        var totalHeight = $(window).height();
        var headerHeight = $("header").height();
        var footerHeight = $("footer").height();
        var b = totalHeight - headerHeight - footerHeight;
        $(element).height(b);
    }
</script>

OliveInvest/Views/CurrentDevelopment/Index.cshtml
<script src="~/Scripts/CurrentDevelopment/CurDev.js"></script>
<script src="~/Scripts/CurrentDevelopment/CurrentDevelopment.js"></script>

<div class="currentHeadline">
    <h1>PONTUS HOTEL AND RESIDENCES</h1>
    <ul>
        <li class="forHavrz" id="descriptionBtn">DESCRIPTION ▼</li>
        <li class="forHavrz" id="floorplansBtn">FLOORPLANS ▼</li>
    </ul>
</div>
<div id="cont1">
    <p>Named after the Greek god of sea, Pontus, the luxury hotel and residences is set on the main <br />Tivat ponta (small jetty). Overlooking the blue waters of the bay, the 9 apartments with <br /> Adriatic inspired interiors and exclusive restaurant Pontus, appeal to all senses.</p>
</div>
<div id="cont2">
    <div id="floorMenu">
        <ul>
            <li><a class="planLink" id="garage"><span class="strelicaSpan"></span>GARAGE</a></li>
            <li><a class="planLink" id="groundFloor"><span class="strelicaSpan">►</span>GROUND FLOOR</a></li>
            <li><a class="planLink" id="firstFloor"><span class="strelicaSpan"></span>FIRST FLOOR</a></li>
            <li><a class="planLink" id="secondFloor"><span class="strelicaSpan"></span>SECOND FLOOR</a></li>
            <li><a class="planLink" id="roof"><span class="strelicaSpan"></span>ROOF</a></li>
        </ul>
    </div>
    <div id="plans">
        <img src="~/Images/Floor%20Plans/Ground%20Floor.png" />
    </div>

</div>

<div class="sliderButtons">
</div>
<div class="currentDev">
    <span class="mojText"></span>

</div>
<style>
    #preload-05 {
        background: url('/Images/CurrentBg/Hotel%20Pontus,%20Tivat%20-5.jpg') no-repeat -9999px -9999px;
    }

    #preload-04 {
        background: url('/Images/CurrentBg/Hotel%20Pontus,%20Tivat%20-4.jpg') no-repeat -9999px -9999px;
    }

    #preload-03 {
        background: url('/Images/CurrentBg/Hotel%20Pontus,%20Tivat%20-3.jpg') no-repeat -9999px -9999px;
    }

    #preload-02 {
        background: url('/Images/CurrentBg/Hotel%20Pontus,%20Tivat%20-2.jpg') no-repeat -9999px -9999px;
    }

    #preload-01 {
        background: url('/Images/CurrentBg/Hotel%20Pontus,%20Tivat%20-1.jpg') no-repeat -9999px -9999px;
    }
</style>

OliveInvest/Views/DestinationBokaBay/Index.cshtml
<div class="destinationPage">
    <div class="destinContent">
        <h1>DESTINATION BOKA BAY</h1>
        <p>Nested in between the cliffs of mount Lovcen and the Mediterranean waves, the Boka Bay <br/> represents a geographical miracle. Europe’s southernmost fjord, reflecting old town buildings and <br /> fortifications in its waters, is a UNESCO protected heritage site. The past and the present of this <br /> picturesque bay is characterized by a vibrant Mediterranean culture and rich maritime history.<br /><br />For more info visit: www.visitmontenegro.net</p>
    </div>
</div>
<script>
    $(document).ready(function () {
        setHeight("#body");
        setHeight(".destinationPage");
        centroralizer('.destinContent');
        window.onload(function () {
            setHeight("#body");
            setHeight(".destinationPage");
        });
    });
 


    $(window).resize(function () {
        setHeight("#body");
        setHeight(".destinationPage");
        centroralizer(".destinContent");
    });

    function centroralizer(element) {
        var totalWidth = $(window).width();
        var elementWidth = $(element).width();
        var vrednost = (totalWidth - elementWidth) / 2;
        $(element).css('left', vrednost);
    }

    function setHeight(element) {
        var totalHeight = $(window).height();
        var headerHeight = $("header").height() -118;
        var footerHeight = $("footer").height();
        var b = totalHeight - headerHeight - footerHeight - 60 - 31;
        $(element).height(b);
    }
</script>

OliveInvest/Views/FutureDevelopments/Index.cshtml
<div class="futurePage">
    <h1>STAY CONNECTED FOR MORE INFORMATIONS<br />ABOUT FUTURE DEVELOPMENTS</h1>
</div>
<script>
    $(document).ready(function () {

        setHeight("#body");
        setHeight(".futurePage");
    });

    $(window).resize(function () {
        setHeight("#body");
        setHeight(".futurePage");
    });

    function setHeight(element) {
        var totalHeight = $(window).height();
        var headerHeight = $("header").height();
        var footerHeight = $("footer").height();
        var b = totalHeight - headerHeight - footerHeight;
        $(element).height(b);
    }


</script>

OliveInvest/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

OliveInvest/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

OliveInvest/Views/Home/Index.cshtml
<script src="~/Scripts/Slider/MySlider.js"></script>
<script src="~/Scripts/Home/Home.js"></script>
<div class="homePage">
    <div class="mojText"></div>
</div>
<div class="sliderButtons">
</div>
<style>
    #preload-03 {
        background: url('/Images/Backgrounds/Olive%20invest-Third%20slidet.jpg') no-repeat -9999px -9999px;
    }
    #preload-02 {
        background: url('/Images/Backgrounds/Olive%20invest-second%20slidet.jpg') no-repeat -9999px -9999px;
    }
    #preload-01 {
        background: url('/Images/Backgrounds/Olive%20invest-first%20slidet.jpg') no-repeat -9999px -9999px;
    }
</style>

OliveInvest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    <link href='http://fonts.googleapis.com/css?family=Prata' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Maven+Pro:500,700' rel='stylesheet' type='text/css'>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <header>
        <div class="top-headline">
            <a style="outline:none; text-decoration:none" href="@Url.Action("Index","Home")"><img src="~/Images/Logo/Olive%20Invest%20Logo.png" /></a>
            <div class="Language">
            </div>
        </div>
        <nav>
            <ul id="menuitems">
                @*/prime reale estate, pontus montenegro oliv invest, montenegro reale estate /*@
                <li><a href="@Url.Action("Index","Home")">HOME</a></li>
                <li><a class="menuitem" href="@Url.Action("Index","AboutUs")">ABOUT US</a></li>
                <li><a class="menuitem" href="@Url.Action("Index","CurrentDevelopment")">CURENT DEVELOPMENT</a></li>
                <li><a class="menuitem" href="@Url.Action("Index","FutureDevelopments")">FUTURE DEVELOPMENTS</a></li>
                <li><a class="menuitem" href="@Url.Action("Index","DestinationBokaBay")">DESTINATION BOKA BAY</a></li>
                <li><a class="menuitem" href="@Url.Action("Index","ContactUs")">CONTACT US</a></li>
            </ul>
        </nav>
    </header>
    <div id="body">
        @RenderBody()
    </div>
    <footer>
        <ul>
            <li><img src="~/Images/Icons/Phone.png" />+382 67 914 8277</li>
            <li><img src="~/Images/Icons/Email.png" />info@oliveinvest.com</li>
            <li><img src="~/Images/Icons/Location.png" />Šetalište Iva Vizina, 85320, Tivat, Montenegro</li>
        </ul>
    </footer>
    <script>
        $('.menuitem').each(function () {
            if (this.href == window.location.href) {
                $(this).addClass("activemenu");
            }
        });
    </script>
</body>

</html>